//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp7.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_Database {
            get {
                return ((string)(this["Txt_Database"]));
            }
            set {
                this["Txt_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_Ins_Layout_2D {
            get {
                return ((string)(this["Txt_Ins_Layout_2D"]));
            }
            set {
                this["Txt_Ins_Layout_2D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_Cable_Pulled {
            get {
                return ((bool)(this["Chx_Cable_Pulled"]));
            }
            set {
                this["Chx_Cable_Pulled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_Cable_Ready {
            get {
                return ((bool)(this["Chx_Cable_Ready"]));
            }
            set {
                this["Chx_Cable_Ready"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_Ter_Done {
            get {
                return ((bool)(this["Chx_Ter_Done"]));
            }
            set {
                this["Chx_Ter_Done"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_Ins_Layout_2C {
            get {
                return ((string)(this["Txt_Ins_Layout_2C"]));
            }
            set {
                this["Txt_Ins_Layout_2C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_Ins_Layout_3A {
            get {
                return ((string)(this["Txt_Ins_Layout_3A"]));
            }
            set {
                this["Txt_Ins_Layout_3A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_No_Tray {
            get {
                return ((bool)(this["Chx_No_Tray"]));
            }
            set {
                this["Chx_No_Tray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_No_Equipment {
            get {
                return ((bool)(this["Chx_No_Equipment"]));
            }
            set {
                this["Chx_No_Equipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_Ins_Layout_2B {
            get {
                return ((string)(this["Txt_Ins_Layout_2B"]));
            }
            set {
                this["Txt_Ins_Layout_2B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_MC_1st {
            get {
                return ((string)(this["Txt_MC_1st"]));
            }
            set {
                this["Txt_MC_1st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_MC_2rd {
            get {
                return ((string)(this["Txt_MC_2rd"]));
            }
            set {
                this["Txt_MC_2rd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_MC_3th {
            get {
                return ((string)(this["Txt_MC_3th"]));
            }
            set {
                this["Txt_MC_3th"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_MC_1st {
            get {
                return ((bool)(this["Chx_MC_1st"]));
            }
            set {
                this["Chx_MC_1st"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_MC_2rd {
            get {
                return ((bool)(this["Chx_MC_2rd"]));
            }
            set {
                this["Chx_MC_2rd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chx_MC_3th {
            get {
                return ((bool)(this["Chx_MC_3th"]));
            }
            set {
                this["Chx_MC_3th"] = value;
            }
        }
    }
}
